name: Run Frontend Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Specify the Node.js version you need

    - name: Install Dependencies
      run: |
        cd app
        npm ci

    - name: Run Tests
      run: |
        cd app
        npm test
