name: Run Backend Tests

on: push
  # all pushes will run checks
    # branches: [ "32-create-cicd-workflow" ] # for specific branch push
  # pull_request: # for all pull requests
    # branches: [dev] # for specific branch pull request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' # Specify the Python version you need
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: python backend/backend_test.py
